### ISSUE TITLE
How to Use UFO to compile a project

### ISSUE THREAD

**Issue by JsHuang** [parasol-aser/UFO#2]
Hi, I want to use UFO to test some open source softwares, but how can I compile them with UFO?
the usage example is only a single test file, could you please give some more examples ?

**Comment by ivlzme** [comment]
Exact usage will of course vary from project to project, but I can speak specifically for running UFO on the Google Chrome web browser. I will describe the instruction sequence for compiling Chrome with UFO, and hopefully you should be able modify the process to compile other open-source software.
###### (Note: this is ***not*** the complete build sequence. If you wish for more specifics/help, open another issue, or simply refer to the Chromium documentation)

First, follow the steps at https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_build_instructions.md/ (This is for Linux) to get the Chrome source code and set up for the build. Then, follow the instructions in this project to build LLVM containing the tsan outfitted with UFO. At this point, you should have `/$your_llvm_build_dir$/bin/clang`. Chrome uses GN and Ninja to build (you can research more into their build system independently) and allows a user to specify a custom clang binary to be used. Simply configure it to use our new clang binary by editing the `args.gn` file contained in the Chrome source directory (`src/out/Default/`) like this:
```
clang_base_path="/$your_llvm_build_dir$"
clang_use_chrome_plugins=false
is_tsan=true
enable_nacl=false
is_debug=false
```
After that, follow the documentation's steps to build the project. Then you can trace program execution by running chrome with the UFO flags. Ex. 
```
UFO_ON=1 UFO_CALL=1 UFO_TL_BUF=512 ./src/out/Default/chrome --no-sandbox
```
Hope this helps.

**Comment by JsHuang** [comment]
Thanks, hope for your stable version.
