### ISSUE TITLE
Hi where can I find the confirmed UAFs. 

### ISSUE THREAD

**Issue by gangfan** [parasol-aser/UFO#4]
Dear Andrew, 

Do you know where I can find those confirmed/detected UAF reports as mentioned in the paper? 

Thanks

**Comment by ivlzme** [comment]
Hello Gang,

If you are referring to the UAFs detected in Firefox/Chrome, we have submitted bug reports directly to the developers. However, we cannot disclose these issues to the public until they are resolved or verified to be false positives. It is unfortunate, but verifying cases as complex as these takes an incredible amount of time.

Hope this helps.

**Comment by gangfan** [comment]
Understand and thank you for your reply.
