### ISSUE TITLE
Java Exception in Docker

### ISSUE THREAD

**Issue by qspark-zz** [parasol-aser/UFO#6]
I am trying to run UFO using docker but I keep getting exception when trying to run `java -jar ufo-predict/runufo.jar`

The error message is exception in "main":

```
Exception in thread "main" java.lang.NullPointerException
	at aser.ufo.misc.Addr2line.<init>(Addr2line.java:40)
	at aser.ufo.Session.init(Session.java:56)
	at aser.ufo.UFOMain.main(UFOMain.java:27)
```

I edited my `config.properties` to be
```
app_name=test
# trace directory to be analyzed
trace_dir=./ufo_traces
# solver timeout seconds
solver_time=120
#default symbolizer
symbolizer=atos
# solver_mem MB
solver_mem=2000
# window size
window_size=100000
# fast detect does not solve constraints to verify UAFs
fast_detect=false

```

and also tried changing the second line to `trace_dir=./ufo_test_trace` and `trace_dir=./ufo_test_trace_22` to match the directory name of `ufo_test_trace_22` in the ufo directory.

**Comment by ivlzme** [comment]
@qspark, is the variable `trace_dir` correctly set to the **relative path** (or absolute, if you wish) of the directory of generated traces? For example, because of the way that the UFO directory is structured, the correct value should likely be `../ufo_test_trace_22`.

**Comment by qspark-zz** [comment]
Didn't see that I was missing a dot. I fixed the error by changing it to be `trace_dir=../ufo_test_trace_22`, being in the directory `ufo-predict`
and running `java -jar ../ufo-predict/runufo.jar`

Thanks!
